# Generated by Django 4.1.3 on 2022-12-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='added_date',
            field=models.DateField(auto_now=True),
        ),
    ]
