# Generated by Django 4.1.3 on 2023-01-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0002_alter_lists_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
