# Generated by Django 4.1.3 on 2023-01-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0003_alter_lists_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lists',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
